apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-virtualgateway
spec:
  hosts:
    - "*"
  gateways:
    - {{ .Release.Name }}-virtualservice
  http:
    - name: primary  # ✅ Ensure this name matches Rollout configuration
      match:
        - uri:
            prefix: "/argo-rollouts"  # ✅ Keep prefix
      route:
        - destination:
            host: cafeapp-argo-rollout-cafeweb-stable  # ✅ Stable service
            port:
              number: 80
          weight: 100
        - destination:
            host: cafeapp-argo-rollout-cafeweb-canary  # ✅ Canary service
            port:
              number: 80
          weight: 0
