apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-virtualservice
spec:
  hosts:
    - "*"
  gateways:
    - cafeapp-helm-gateway
  http:
    - name: primary
      match:
        - uri:
            prefix: "/argo-rollouts"
      route:
        - destination:
            host: cafeapp-argo-rollout-cafeweb-stable.default.svc.cluster.local  # ✅ Add namespace explicitly
            port:
              number: 80
          weight: 100
        - destination:
            host: cafeapp-argo-rollout-cafeweb-canary.default.svc.cluster.local  # ✅ Add namespace explicitly
            port:
              number: 80
          weight: 0

# spec:
#   hosts:
#     - "*"
#   gateways:
#     - {{ .Release.Name }}-virtualgateway
#   http:
#     - name: primary  # ✅ Ensure this name matches Rollout configuration
#       match:
#         - uri:
#             prefix: "/argo-rollouts"  # ✅ Keep prefix
#       route:
#         - destination:
#             host: cafeapp-argo-rollout-cafeweb-stable  # ✅ Stable service
#             port:
#               number: 80
#           weight: 100
#         - destination:
#             host: cafeapp-argo-rollout-cafeweb-canary  # ✅ Canary service
#             port:
#               number: 80
#           weight: 0
