apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cafeapp-helm-rollout
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/neehar2601/Cafe_Dynamic_Website.git'
    targetRevision: HEAD
    path: Deploy/progressive_delivery_argo_rollouts
  helm:
    valueFiles:
      - values-dev.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
