apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: cafeapp
  labels:
    app: cafeapp
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: cafeapp
  clusterIP: None  # Makes it a headless service for internal communication
