replicaCount: 1

mysql:
  image: sreedocker123/mompopcafedb:v1
  database: mom_pop_db
  user: root

cafeweb:
  image: neehar2601/argo-rollouts
  tag: v3

persistentVolume:
  size: 10Gi
  hostPath: "/mnt/data/dev1"
  
config:
  showServerInfo: "false"
  timeZone: "America/New_York"
  currency: "$"
  #db_url: "cafeapp-helm-mysql"
  db_name: "mom_pop_db"
  db_user: "root"
  db_password: "Msois@123"
