apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Release.Name }}-cafeweb-rollout
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: cafeapprollout1
      tier: frontend
  template:
    metadata:
      labels:
        app: cafeapprollout1
        tier: frontend
    spec:
      containers:
      - name: cafeweb
        image: {{ .Values.cafeweb.image }}:{{ .Values.cafeweb.tag }}
        ports:
        - containerPort: 80
        env:
        - name: MYSQL_HOST
          value: {{ .Release.Name }}-mysql
        - name: MYSQL_DATABASE
          value: {{ .Values.mysql.database }}
        - name: MYSQL_USER
          value: {{ .Values.mysql.user }}
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-mysql-pass
              key: password
        volumeMounts:
        - name: app-config-volume
          mountPath: /var/www/html/argorolloutsbg/getAppParameters.php
          subPath: getAppParameters.php
      volumes:
      - name: app-config-volume
        configMap:
          name: {{ .Release.Name }}-cafeweb-config
  strategy:
    blueGreen:
      activeService: {{ .Release.Name }}-cafeweb-stable
      previewService: {{ .Release.Name }}-cafeweb-preview
      autoPromotionEnabled: true  
      prePromotionAnalysis:
        templates:
        - templateName: {{ .Release.Name }}-rollout-analysis
      postPromotionAnalysis:
        templates:
        - templateName: {{ .Release.Name }}-rollout-analysis
