apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mysql
  labels:
    app: cafeapprollout
spec:
  type: ClusterIP
  ports:
    - port: 3306
  selector:
    app: cafeapprollout
    tier: mysql
