apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: cafeapp-argo-rolloutbg-virtualservice
  namespace: default
spec:
  hosts:
    - "*"
  gateways:
    - cafeapp-helm-gateway
  http:
    - name: "primary"
      match:
        - uri:
            prefix: /argo-rolloutsbg
        - uri:
            prefix: /argo-rolloutsbg/
      route:
        - destination:
            host: cafeapp-argo-rolloutbg-cafeweb-stable.default.svc.cluster.local
            port:
              number: 80
          weight: 100
